services:
  backend:
    build: .
    command: npm run server
    ports:
      - "3000:3000"
    volumes:
      - ./src/data:/app/src/data
      - ./server.js:/app/server.js
    environment:
      - NODE_ENV=development
      - DEBUG=true
    networks:
      - app-network

  frontend:
    build: .
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
