services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./src/data:/app/src/data
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=true

volumes:
  node_modules:
