services:
  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=employee_movements
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - CORS_ORIGIN=http://localhost:3001
      # Use service name for internal Docker networking
      - VITE_API_URL=http://backend:3000
      # Database Configuration
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=employee_movements
      - DB_USER=app_user
      - DB_PASSWORD=app_password
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      # Use service name for internal Docker networking
      - VITE_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
